version: '3.8'

services:
  postgres:
    build: .
    container_name: ptscribe_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data

volumes:
  pgdata:

# docker-compose --env-file .env.local up
# docker exec -it ptscribe_postgres_container bash